export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const CHANGE_STATUS ="CHANGE_STATUS"