


export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const FETCH_PRODUCTS_REQUEST= "FETCH_PRODUCTS_REQUEST";
export const  FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

export const FETCH_PRODUCT_REQUEST= "FETCH_PRODUCT_REQUEST";
export const  FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILED = "FETCH_PRODUCT_FAILED";


export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";